plugins { id 'com.android.application' }

android {
    namespace 'com.ebrahilok.trazo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ebrahilok.trazo'
        minSdk 24
        targetSdk 36
        versionCode 6
        versionName '2.3'
    }
}

dependencies { implementation 'androidx.core:core:1.15.0' }
